type Ingredient = {
  id: string
  ingredient: string
  category: string
  image: string
  calories: number
}

export const DUMMY: Ingredient[] = [
  {
    id: '1',
    ingredient: 'green leaf lettuce',
    category: 'vegetable',
    image: '',
    calories: 8,
  },
  {
    id: '2',
    ingredient: 'Bok choy',
    category: 'vegetable',
    image: '',
    calories: 7,
  },
  {
    id: '3',
    ingredient: 'Kale',
    category: 'vegetable',
    image: '',
    calories: 10,
  },
  {
    id: '4',
    ingredient: 'red cabbage',
    category: 'vegetable',
    image: '',
    calories: 10,
  },
  {
    id: '5',
    ingredient: 'carrots',
    category: 'vegetable',
    image: '',
    calories: 12,
  },
  {
    id: '6',
    ingredient: 'avocado',
    category: 'fruit',
    image: '',
    calories: 120,
  },
  {
    id: '7',
    ingredient: 'Tomato',
    category: 'fruit',
    image: '',
    calories: 18,
  },
  {
    id: '8',
    ingredient: 'pineapple',
    category: 'fruit',
    image: '',
    calories: 25,
  },
  {
    id: '9',
    ingredient: 'mix berries',
    category: 'fruit',
    image: '',
    calories: 28,
  },
  {
    id: '10',
    ingredient: 'Corn',
    category: 'fruit',
    image: '',
    calories: 43,
  },
  {
    id: '11',
    ingredient: 'Grilled Shrimp',
    category: 'protein',
    image: '',
    calories: 98,
  },
  {
    id: '12',
    ingredient: 'Grilled Chicken Breast',
    category: 'protein',
    image: '',
    calories: 165,
  },
  {
    id: '13',
    ingredient: 'Bacon',
    category: 'protein',
    image: '',
    calories: 108,
  },
  {
    id: '14',
    ingredient: 'Smoked Salmon',
    category: 'protein',
    image: '',
    calories: 58,
  },
  {
    id: '15',
    ingredient: 'Grilled Beef',
    category: 'protein',
    image: '',
    calories: 250,
  },
  {
    id: '16',
    ingredient: 'Crouton',
    category: 'dressing',
    image: '',
    calories: 81,
  },
  {
    id: '17',
    ingredient: 'Barley',
    category: 'dressing',
    image: '',
    calories: 100,
  },
  {
    id: '18',
    ingredient: 'Cashew Nut',
    category: 'dressing',
    image: '',
    calories: 110,
  },
  {
    id: '19',
    ingredient: 'Cream Dressing',
    category: 'dressing',
    image: '',
    calories: 60,
  },
  {
    id: '20',
    ingredient: 'Balsamic Dressing',
    category: 'dressing',
    image: '',
    calories: 26,
  },
  {
    id: '21',
    ingredient: 'Japanese Shoyu',
    category: 'dressing',
    image: '',
    calories: 15,
  },
  {
    id: '22',
    ingredient: 'Seafood Cream Dressing',
    category: 'dressing',
    image: '',
    calories: 75,
  },
  {
    id: '23',
    ingredient: 'Roast Sesame Dressing',
    category: 'dressing',
    image: '',
    calories: 60,
  },
]
